name: Update Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Notify
        run: echo 'GitHub Pages will auto-update after push to main.'
